[colors]
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black = '#282c34'
red = '#ef596f'
green = '#89ca78'
yellow = '#e5c07b'
blue = '#61afef'
magenta = '#d55fde'
cyan = '#2bbac5'
white = '#abb2bf'

# Bright colors
[colors.bright]
black = '#5c6370'
red = '#d19a66'
green = '#89ca78'
yellow = '#e2be7d'
blue = '#61afef'
magenta = '#d55fde'
cyan = '#2bbac5'
white = '#abb2bf'

[colors.selection]
background = '#61afef'
foreground = '#282c34'
